version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "25037:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - FLASK_RUN_HOST=0.0.0.0
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      args:
        - NODE_ENV=production
        # Thêm dòng này để GHI ĐÈ lại URL API mặc định trong config.js
        # - REACT_APP_API_URL=http://103.253.20.13:25037 
        # Trong config.js có dòng [REACT_APP_API_URL=http://103.253.20.13:25037] cho production rồi 
    ports:
      - "25038:3000"
    environment:
      - NODE_ENV=production
      # Thêm dòng này để GHI ĐÈ lại URL API mặc định trong config.js
      # - REACT_APP_API_URL=http://103.253.20.13:25037  
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 